/* eslint-disable no-unused-vars */
/* eslint-disable camelcase */

// Generated by https://quicktype.io

export interface PlacesResponse {
	type: string;
	query: string[];
	features: Feature[];
	attribution: string;
}

export interface Feature {
	id: string;
	type: string;
	place_type: string[];
	relevance: number;
	properties: Properties;
	text_es: string;
	place_name_es: string;
	text: string;
	place_name: string;
	center: number[];
	geometry: Geometry;
	context: Context[];
}

export interface Context {
	id: string;
	text_es: string;
	language_es?: Language;
	text: string;
	language?: Language;
	wikidata?: string;
	short_code?: Language;
}

export enum Language {
	Es = 'es',
	EsSE = 'ES-SE',
}

export interface Geometry {
	type: string;
	coordinates: number[];
}

export interface Properties {
	accuracy: string;
}
